### ISSUE TITLE
binder_linux not found

### ISSUE THREAD

**Issue by bdodroid** [sailfish-on-dontbeevil/kernel-adaptation-pinephonepro#1]
Trying to get Waydroid running on a pinephone pro fails with a "binder_linux not found" error.
Running "waydroid init" just spits out:

```
Failed to load binder driver
modprobe: FATAL: Module binder_linux not found in directory /lib/modules/6.0.7-pinephonepro
ERROR: Binder node "binder" for waydroid not found 
```

**Comment by DrYak** [comment]
For reference:

This is the relevant bit in the Megi kernel's `/proc/config.gz`:

```sh
#
# Android
#
# CONFIG_ANDROID_BINDER_IPC is not set
# end of Android
```

Whereas this is the same section on SailfishX running with kernel 4.19.248 on my (broken) Xperia 10iii (which CAN run Jolla AppSupport/aliendalvik):

```sh
#
# Android
#
CONFIG_ANDROID=y
CONFIG_ANDROID_BINDER_IPC=y
CONFIG_ANDROID_BINDERFS=y
CONFIG_ANDROID_BINDER_DEVICES="binder,vndbinder,hwbinder,puddlejumper,vndpuddlejumper,hwpuddlejumper"
# CONFIG_ANDROID_BINDER_IPC_SELFTEST is not set
# CONFIG_LIBNVDIMM is not set
# CONFIG_DAX is not set
CONFIG_NVMEM=y
# CONFIG_NVMEM_SYSFS is not set
CONFIG_QCOM_QFPROM=y
CONFIG_NVMEM_SPMI_SDAM=y
```

And on my Pinebook Pro on Manjaro ARM with kernel 6.5.3:
```sh
#
# Android
#
CONFIG_ANDROID_BINDER_IPC=y
CONFIG_ANDROID_BINDERFS=y
CONFIG_ANDROID_BINDER_DEVICES="binder,hwbinder,vndbinder"
# CONFIG_ANDROID_BINDER_IPC_SELFTEST is not set
# end of Android
```

**Comment by DrYak** [comment]
Also, according to [porter's tasks](https://github.com/sailfishos-open/waydroid#porter-tasks) , there are [a bunch of other kernel drivers required](https://github.com/waydroid/waydroid/blob/lineage-17.1/scripts/check-kernel-config.sh#L16), of which not all seem present:

```sh
[nemo@PinePhonePro ~]$ zgrep -E 'CONFIG_SW_SYNC_USER|CONFIG_NET_CLS_CGROUP|CONFIG_CGROUP_NET_CLASSID|CONFIG_VETH|CONFIG_BRIDGE|CONFIG_NETFILTER_XT_TARGET_CHECKSUM' /proc/config.gz 
# CONFIG_BRIDGE_NETFILTER is not set
# CONFIG_NETFILTER_XT_TARGET_CHECKSUM is not set
# CONFIG_BRIDGE_NF_EBTABLES is not set
CONFIG_BRIDGE=y
CONFIG_BRIDGE_IGMP_SNOOPING=y
# CONFIG_BRIDGE_VLAN_FILTERING is not set
# CONFIG_BRIDGE_MRP is not set
# CONFIG_BRIDGE_CFM is not set
CONFIG_NET_CLS_CGROUP=y
CONFIG_CGROUP_NET_CLASSID=y
CONFIG_VETH=y
```

- `CONFIG_NETFILTER_XT_TARGET_CHECKSUM` isn't set in the current kernel, not even as a module.
  - (Xperia 10iii and Pinebook Pro have it built-in and as a module, respectively).
- I can't manage to find `CONFIG_SW_SYNC_USER` at all in 6.5.x configurations.
  -  Is it from some older kernel versions?
  - The entry doesn't even exist on the Xperia 10iii nor Pinebook Pro. Nor even my Opensuse Tumbleweed workstation).
  - The closest I can find is `CONFIG_SW_SYNC` which isn't set on none of the Aarch64 device.

**Comment by piggz** [comment]
Yes, CONFIG_SW_SYNC_USER is only until 4.5

**Comment by DrYak** [comment]
Works with the new kernel. Thanks.
